# Generated by Django 3.1.5 on 2021-01-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaCorrente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=20)),
                ('balance', models.DecimalField(auto_created=0, decimal_places=2, max_digits=9999999999999999)),
            ],
            options={
                'db_table': 'contacorrente',
            },
        ),
    ]
