# Generated by Django 3.1.5 on 2021-01-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacorrente',
            name='accountNumber',
            field=models.CharField(auto_created=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='contacorrente',
            name='balance',
            field=models.DecimalField(auto_created=True, decimal_places=2, max_digits=9999999999999999),
        ),
    ]
