# Generated by Django 3.1.5 on 2021-01-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210120_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacorrente',
            name='balance',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=999999999999999),
        ),
    ]
