# Generated by Django 3.1.5 on 2021-01-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20210120_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacorrente',
            name='accountNumber',
            field=models.CharField(auto_created=True, help_text='Número da conta já existente. Por favor insira outro.', max_length=100000, unique=True),
        ),
    ]
