# Generated by Django 3.1.5 on 2021-01-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20210120_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacorrente',
            name='accountNumber',
            field=models.CharField(auto_created=True, max_length=100000, unique=True),
        ),
        migrations.AlterField(
            model_name='contacorrente',
            name='id',
            field=models.PositiveSmallIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
