# Generated by Django 3.1.5 on 2021-01-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20210120_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacorrente',
            name='id',
            field=models.CharField(auto_created=True, editable=False, max_length=9999999999, primary_key=True, serialize=False, unique=True),
        ),
    ]
