# Generated by Django 3.1.5 on 2021-01-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_auto_20210120_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacorrente',
            name='id',
            field=models.CharField(max_length=9999999990, primary_key=True, serialize=False),
        ),
    ]
