# Generated by Django 3.1.5 on 2021-01-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_auto_20210120_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacorrente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
