# Generated by Django 3.1.5 on 2021-01-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_auto_20210121_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacorrente',
            name='accountNumber',
            field=models.CharField(auto_created=True, editable=False, max_length=100000, unique=True),
        ),
    ]
