# Generated by Django 3.1.5 on 2021-01-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_auto_20210121_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacorrente',
            name='accountNumber',
            field=models.CharField(auto_created=True, max_length=100000, unique=True),
        ),
        migrations.AlterField(
            model_name='contacorrente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
